package Exception;

public class ThrowsException {
	int divison(int a, int b) throws ArithmeticException{
		int t = a/b;
		return t;
	}
	public static void main(String[] args) {
		ThrowsException obj = new ThrowsException();
		try {
			System.out.println("Result of division is : "+obj.divison(25, 3));
		} catch (ArithmeticException e) {
			System.out.println("You shouldn't divide number by zero.");
			// TODO: handle exception
		}
	}

}
